# Generated by Django 2.1.1 on 2018-09-15 15:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pugorugh', '0006_auto_20180914_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdog',
            name='status',
            field=models.CharField(choices=[('l', 'liked'), ('d', 'disliked'), ('u', 'undecided')], default='u', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='userdog',
            unique_together={('user', 'dog')},
        ),
    ]
